package rpg.game.Viewer;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import rpg.game.Interogate_and_insert.InterrogateAndCheckPlayer;
import rpg.game.Model_base.Caracter;
import rpg.game.*;
import rpg.game.Storage.Read_Hero_from_file;
import rpg.game.Storage.Read_Hero_from_file;
import rpg.game.Storage.Save_Hero_to_file;
import sun.rmi.runtime.Log;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Bb
 */
public class OldPlayer extends javax.swing.JPanel {

//    private List<String> readFile(String Saved_hero)
//    {
//        List<String> records = new ArrayList<String>();
//        try
//        {
//            BufferedReader reader = new BufferedReader(new FileReader(Saved_hero));
//            String line;
//            while ((line = reader.readLine()) != null)
//            {
//                records.add(line);
//            }
//            reader.close();
//            return records;
//        }
//        catch (Exception e)
//        {
//            System.err.format("Exception occurred trying to read '%s'.", Saved_hero);
//            e.printStackTrace();
//            return null;
//        }
//    }
//    private void insert_atributes(List<String> saved_hero) {
//        int i = 0;
//        while (1 < saved_hero.size()){
//            System.out.println(saved_hero.get( i ));
//            i++;
//        }
//    }



    public OldPlayer() {
        initComponents();
        Read_Hero_from_file.readHeroFromFile();
        Read_Hero_from_file.readHeroes();
        Read_Hero_from_file.EndOfStreamSignal.try_to_add_hero_to_list();

        //        Caracter.Hero hero = null;
//Save_Hero_to_file.readHeroFromFile();
        Save_Hero_to_file.read_herooo();
//        String [] ss = Messenger.enumStatus(newcaracter);
//        int i = 0;
//        while(i < 12){
//            StatusOutput.append( ss[i]);
//            i++;
//
//        }
//        //List<String> Saved_hero = new ArrayList<String>();
//       // Saved_hero =  readFile("Saved_hero.txt");
//       // insert_atributes(Saved_hero);

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Continue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StatusOutput = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Old_Heroes_list = new javax.swing.JList<>();

        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });

        StatusOutput.setColumns(20);
        StatusOutput.setRows(5);
        StatusOutput.setText("Status");

        jScrollPane1.setViewportView(StatusOutput);

        Old_Heroes_list.setModel(Old_Heroes_list.getModel());
        Old_Heroes_list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Old_Heroes_listValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(Old_Heroes_list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Continue, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Continue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1))
                                .addContainerGap())
        );
    }// </editor-fold>

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        //InterrogateAndCheckPlayer.continue_after_insertion( newcaracter, topFrame );        // TODO add your handling code here:
    }

    private void Old_Heroes_listValueChanged(javax.swing.event.ListSelectionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JButton Continue;
    private javax.swing.JList<String> Old_Heroes_list;
    private javax.swing.JTextArea StatusOutput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration
}

