package rpg.game.Viewer;
import rpg.game.Interogate_and_insert.InterrogateAndCheckPlayer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import static java.awt.Window.getWindows;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bb
 */
public class Panel1New_Continue extends javax.swing.JFrame {

    public static  int this_player_new_old;
    /**
     * Creates new form Panel1New_Continue
     */
    public Panel1New_Continue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(109, 91, 128));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(70, 105, 245));
        jButton1.setText("New Player");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        NewPlayer newplayer = new NewPlayer();
        this.setContentPane(newplayer);
        this.revalidate();
        InterrogateAndCheckPlayer.save_frame( this );
      /*  Container pane = Panel1New_Continue.this.getContentPane();
                //  Window[] pane = Panel1New_Continue.getWindows();
                pane.remove(Panel1New_Continue.this);
                //pane.remove(MyPanel.this);
                NewPlayer otherPanel = new NewPlayer();
                otherPanel.add(new NewPlayer());
                pane.add(otherPanel);
                pane.revalidate();*/
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        OldPlayer oldplayer = new OldPlayer();
        this.setContentPane(oldplayer);
        this.revalidate();
        InterrogateAndCheckPlayer.save_frame( this );
    }

        /*String cc = evt.toString();
        System.out.println(cc);
        Container pane = super.getContentPane();
        //  Window[] pane = Panel1New_Continue.getWindows();
        //Panel1New_Continue.this.isUndecorated();
        //pane.remove(MyPanel.this);

        String vcc = super.getContentPane().toString();
        System.out.println(vcc);
        //pane.
        NewPlayer otherPanel = new NewPlayer();
        otherPanel.running();
        pane.removeAll();
        pane.add(otherPanel);
        pane.validate();
        pane.revalidate();
        pane.repaint();*/
    // otherPanel.add(new JLabel("OtherPanel"));
       /* Panel1New_Continue.this.removeAll();
        Panel1New_Continue.this.add(otherPanel);
        Panel1New_Continue.this.repaint();
        Panel1New_Continue.this.revalidate();
        Container pane = frame.getContentPane();
        pane.remove(MyPanel.this);
        JPanel otherPanel = new JPanel();
        otherPanel.add(new JLabel("OtherPanel"));*/
    //initComponents();
    // pane.revalidate();
    // System.out.println("" + pane.getAccessibleContext());
    // pane.removeAll();
    // pane.revalidate();
       /* pane.add(new NewPlayer());
        pane.repaint();
        pane.revalidate();
        pane.repaint();
        pane.revalidate();
        NewPlayer Panel = new NewPlayer();
        Panel.running();
        System.out.println("" + pane.getAccessibleContext());
        // otherPanel.add(new NewPlayer());
            // pane.add(otherPanel);
            //   pane.revalidate();
    }*/

    /*private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        /*javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        NewPlayer player = new NewPlayer();
        layout.replace(this, player);
        this_player_new_old = 2;
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               /* Container pane = Panel1New_Continue.this.getContentPane();
                //  Window[] pane = Panel1New_Continue.getWindows();
                pane.remove(Panel1New_Continue.this);
                //pane.remove(MyPanel.this);
                NewPlayer otherPanel = new NewPlayer();
                otherPanel.add(new NewPlayer());
                pane.add(otherPanel);
                pane.revalidate();
            }
        });
    }*/
    private void PlayerNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel1New_Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel1New_Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel1New_Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel1New_Continue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Panel1New_Continue frame = new Panel1New_Continue();
                //frame.getContentPane().add(new Panel1New_Continue());
                frame.setSize(800, 500);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration
}//